[package]
name = "cargo-mobile"
version = "0.1.0"
authors = ["Brainium Studios LLC", "Francesca Lovebloom <francesca@brainiumstudios.com>"]
edition = "2018"
description = "Rust on mobile made easy!"
documentation = "https://docs.rs/cargo-mobile"
repository = "https://github.com/BrainiumLLC/cargo-mobile"
readme = "README.md"
keywords = ["cargo", "mobile", "ios", "android"]
categories = ["development-tools::cargo-plugins"]
license = "Apache-2.0/MIT"

[[bin]]
name = "cargo-apple"

[[bin]]
name = "cargo-android"

[features]
brainium = []
default = []

[dependencies]
bicycle = { git = "https://github.com/BrainiumLLC/bicycle", rev = "28080e0c6fa4067d9dd1b0f2b7322b6b32178e1f" }
bossy = "0.2.1"
colored = "1.9.3"
deunicode = "1.1.1"
english-numbers = "0.3.3"
env_logger = "0.7.1"
heck = "0.3.1"
home = "0.5.3"
ignore = "0.4.16"
indexmap = "1.3.2"
java-properties = { version = "1.2.0" }
log = "0.4.8"
once-cell-regex = "0.2.1"
path_abs = "0.5.0"
reserved-names = { git = "https://github.com/BrainiumLLC/reserved-names" }
serde = { version = "1.0.105", features = ["derive"] }
structopt = "0.3.12"
textwrap = { version = "0.11.0", features = ["term_size"] }
thiserror = "1.0.20"
toml = { version = "0.5.6", features = ["preserve_order"] }
yes-or-no = { git = "https://github.com/BrainiumLLC/yes-or-no" }

[dev-dependencies]
rstest = "0.6"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.20.0"
core-foundation = "0.7.0"
openssl = "0.10.28"
objc = "0.2.7"
objc_id = "0.1.1"
serde_json = "1.0.50"

[target.'cfg(not(target_os = "macos"))'.dependencies]
ureq = "2.4.0"

[target.'cfg(target_os = "linux")'.dependencies]
freedesktop_entry_parser = "1.1"
lexical-core = "0.7.6"

[build-dependencies]
bicycle = { git = "https://github.com/BrainiumLLC/bicycle", rev = "28080e0c6fa4067d9dd1b0f2b7322b6b32178e1f" }
hit = "0.2.0"
home = "0.5.3"
